### PR TITLE
Created Free Parking Square panel

### PR DESCRIPTION
**Pull request by dustinecker**
Created the free parking square and added the image file.  In the future we might replace with a better image, but this will work for now.

### CODE REVIEW

**Comment by dustinecker** [comment]
Just realized I didn't resize the image. I'll update this in a second!

**Review by Dcbaas — APPROVED** [review]
Looks fine to me. And its my review that matters.

**Comment by dustinecker** [comment]
I just resized the image. The class itself didn't need any changes so that should be good.

**Comment by Dcbaas** [comment]
Gonna pull this

**Pull request merged**
